// ═══ صور — Image-based Questions (500) ═══
// Uses flagcdn.com for flags (stable CDN) and Wikimedia Commons for others

const FLAGS = "https://flagcdn.com/w320";
const WIKI = "https://upload.wikimedia.org/wikipedia/commons/thumb";

module.exports = [

// ╔══════════════════════════════════════╗
// ║  أعلام عربية — Arab Flags (22)      ║
// ╚══════════════════════════════════════╝
{id:10001,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"السعودية",img:`${FLAGS}/sa.png`},
{id:10002,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"مصر",img:`${FLAGS}/eg.png`},
{id:10003,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"الإمارات",img:`${FLAGS}/ae.png`},
{id:10004,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"الأردن",img:`${FLAGS}/jo.png`},
{id:10005,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"لبنان",img:`${FLAGS}/lb.png`},
{id:10006,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"العراق",img:`${FLAGS}/iq.png`},
{id:10007,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"سوريا",img:`${FLAGS}/sy.png`},
{id:10008,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"فلسطين",img:`${FLAGS}/ps.png`},
{id:10009,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"الكويت",img:`${FLAGS}/kw.png`},
{id:10010,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"البحرين",img:`${FLAGS}/bh.png`},
{id:10011,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"قطر",img:`${FLAGS}/qa.png`},
{id:10012,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"عُمان",img:`${FLAGS}/om.png`},
{id:10013,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"اليمن",img:`${FLAGS}/ye.png`},
{id:10014,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"ليبيا",img:`${FLAGS}/ly.png`},
{id:10015,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"تونس",img:`${FLAGS}/tn.png`},
{id:10016,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"الجزائر",img:`${FLAGS}/dz.png`},
{id:10017,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"المغرب",img:`${FLAGS}/ma.png`},
{id:10018,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"السودان",img:`${FLAGS}/sd.png`},
{id:10019,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"موريتانيا",img:`${FLAGS}/mr.png`},
{id:10020,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"الصومال",img:`${FLAGS}/so.png`},
{id:10021,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"جيبوتي",img:`${FLAGS}/dj.png`},
{id:10022,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"جزر القمر",img:`${FLAGS}/km.png`},

// ╔══════════════════════════════════════╗
// ║  أعلام أوروبية — European (30)      ║
// ╚══════════════════════════════════════╝
{id:10023,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"فرنسا",img:`${FLAGS}/fr.png`},
{id:10024,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"ألمانيا",img:`${FLAGS}/de.png`},
{id:10025,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"إيطاليا",img:`${FLAGS}/it.png`},
{id:10026,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"إسبانيا",img:`${FLAGS}/es.png`},
{id:10027,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"بريطانيا",img:`${FLAGS}/gb.png`},
{id:10028,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"البرتغال",img:`${FLAGS}/pt.png`},
{id:10029,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"هولندا",img:`${FLAGS}/nl.png`},
{id:10030,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"بلجيكا",img:`${FLAGS}/be.png`},
{id:10031,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"النمسا",img:`${FLAGS}/at.png`},
{id:10032,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"سويسرا",img:`${FLAGS}/ch.png`},
{id:10033,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"السويد",img:`${FLAGS}/se.png`},
{id:10034,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"النرويج",img:`${FLAGS}/no.png`},
{id:10035,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"الدنمارك",img:`${FLAGS}/dk.png`},
{id:10036,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"فنلندا",img:`${FLAGS}/fi.png`},
{id:10037,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"أيرلندا",img:`${FLAGS}/ie.png`},
{id:10038,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"بولندا",img:`${FLAGS}/pl.png`},
{id:10039,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"التشيك",img:`${FLAGS}/cz.png`},
{id:10040,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"المجر",img:`${FLAGS}/hu.png`},
{id:10041,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"رومانيا",img:`${FLAGS}/ro.png`},
{id:10042,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"اليونان",img:`${FLAGS}/gr.png`},
{id:10043,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"تركيا",img:`${FLAGS}/tr.png`},
{id:10044,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"روسيا",img:`${FLAGS}/ru.png`},
{id:10045,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"أوكرانيا",img:`${FLAGS}/ua.png`},
{id:10046,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"كرواتيا",img:`${FLAGS}/hr.png`},
{id:10047,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"صربيا",img:`${FLAGS}/rs.png`},
{id:10048,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"بلغاريا",img:`${FLAGS}/bg.png`},
{id:10049,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"سلوفاكيا",img:`${FLAGS}/sk.png`},
{id:10050,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"ليتوانيا",img:`${FLAGS}/lt.png`},
{id:10051,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"لاتفيا",img:`${FLAGS}/lv.png`},
{id:10052,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"إستونيا",img:`${FLAGS}/ee.png`},

// ╔══════════════════════════════════════╗
// ║  أعلام آسيوية — Asian (25)          ║
// ╚══════════════════════════════════════╝
{id:10053,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"الصين",img:`${FLAGS}/cn.png`},
{id:10054,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"اليابان",img:`${FLAGS}/jp.png`},
{id:10055,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"الهند",img:`${FLAGS}/in.png`},
{id:10056,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"كوريا الجنوبية",img:`${FLAGS}/kr.png`},
{id:10057,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"تايلاند",img:`${FLAGS}/th.png`},
{id:10058,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"فيتنام",img:`${FLAGS}/vn.png`},
{id:10059,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"إندونيسيا",img:`${FLAGS}/id.png`},
{id:10060,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"ماليزيا",img:`${FLAGS}/my.png`},
{id:10061,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"الفلبين",img:`${FLAGS}/ph.png`},
{id:10062,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"باكستان",img:`${FLAGS}/pk.png`},
{id:10063,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"بنغلاديش",img:`${FLAGS}/bd.png`},
{id:10064,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"سريلانكا",img:`${FLAGS}/lk.png`},
{id:10065,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"نيبال",img:`${FLAGS}/np.png`},
{id:10066,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"ميانمار",img:`${FLAGS}/mm.png`},
{id:10067,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"كمبوديا",img:`${FLAGS}/kh.png`},
{id:10068,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"سنغافورة",img:`${FLAGS}/sg.png`},
{id:10069,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"إيران",img:`${FLAGS}/ir.png`},
{id:10070,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"أفغانستان",img:`${FLAGS}/af.png`},
{id:10071,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"أوزبكستان",img:`${FLAGS}/uz.png`},
{id:10072,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"كازاخستان",img:`${FLAGS}/kz.png`},
{id:10073,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"تركمانستان",img:`${FLAGS}/tm.png`},
{id:10074,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"قيرغيزستان",img:`${FLAGS}/kg.png`},
{id:10075,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"طاجيكستان",img:`${FLAGS}/tj.png`},
{id:10076,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"منغوليا",img:`${FLAGS}/mn.png`},
{id:10077,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"لاوس",img:`${FLAGS}/la.png`},

// ╔══════════════════════════════════════╗
// ║  أعلام الأمريكتين — Americas (20)   ║
// ╚══════════════════════════════════════╝
{id:10078,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"الولايات المتحدة",img:`${FLAGS}/us.png`},
{id:10079,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"كندا",img:`${FLAGS}/ca.png`},
{id:10080,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"المكسيك",img:`${FLAGS}/mx.png`},
{id:10081,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"البرازيل",img:`${FLAGS}/br.png`},
{id:10082,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"الأرجنتين",img:`${FLAGS}/ar.png`},
{id:10083,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"تشيلي",img:`${FLAGS}/cl.png`},
{id:10084,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"كولومبيا",img:`${FLAGS}/co.png`},
{id:10085,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"بيرو",img:`${FLAGS}/pe.png`},
{id:10086,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"فنزويلا",img:`${FLAGS}/ve.png`},
{id:10087,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"الإكوادور",img:`${FLAGS}/ec.png`},
{id:10088,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"كوبا",img:`${FLAGS}/cu.png`},
{id:10089,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"بوليفيا",img:`${FLAGS}/bo.png`},
{id:10090,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"باراغواي",img:`${FLAGS}/py.png`},
{id:10091,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"أوروغواي",img:`${FLAGS}/uy.png`},
{id:10092,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"جامايكا",img:`${FLAGS}/jm.png`},
{id:10093,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"بنما",img:`${FLAGS}/pa.png`},
{id:10094,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"كوستاريكا",img:`${FLAGS}/cr.png`},
{id:10095,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"هندوراس",img:`${FLAGS}/hn.png`},
{id:10096,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"غواتيمالا",img:`${FLAGS}/gt.png`},
{id:10097,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"ترينيداد وتوباغو",img:`${FLAGS}/tt.png`},

// ╔══════════════════════════════════════╗
// ║  أعلام أفريقية — African (25)       ║
// ╚══════════════════════════════════════╝
{id:10098,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"جنوب أفريقيا",img:`${FLAGS}/za.png`},
{id:10099,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"نيجيريا",img:`${FLAGS}/ng.png`},
{id:10100,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"كينيا",img:`${FLAGS}/ke.png`},
{id:10101,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"إثيوبيا",img:`${FLAGS}/et.png`},
{id:10102,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"غانا",img:`${FLAGS}/gh.png`},
{id:10103,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"تنزانيا",img:`${FLAGS}/tz.png`},
{id:10104,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"الكاميرون",img:`${FLAGS}/cm.png`},
{id:10105,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"السنغال",img:`${FLAGS}/sn.png`},
{id:10106,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"ساحل العاج",img:`${FLAGS}/ci.png`},
{id:10107,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"أوغندا",img:`${FLAGS}/ug.png`},
{id:10108,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"موزمبيق",img:`${FLAGS}/mz.png`},
{id:10109,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"مدغشقر",img:`${FLAGS}/mg.png`},
{id:10110,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"أنغولا",img:`${FLAGS}/ao.png`},
{id:10111,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"زيمبابوي",img:`${FLAGS}/zw.png`},
{id:10112,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"تشاد",img:`${FLAGS}/td.png`},
{id:10113,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"النيجر",img:`${FLAGS}/ne.png`},
{id:10114,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"مالي",img:`${FLAGS}/ml.png`},
{id:10115,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"بوركينا فاسو",img:`${FLAGS}/bf.png`},
{id:10116,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"رواندا",img:`${FLAGS}/rw.png`},
{id:10117,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"الكونغو",img:`${FLAGS}/cd.png`},
{id:10118,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"غينيا",img:`${FLAGS}/gn.png`},
{id:10119,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"بنين",img:`${FLAGS}/bj.png`},
{id:10120,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"توغو",img:`${FLAGS}/tg.png`},
{id:10121,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"إريتريا",img:`${FLAGS}/er.png`},
{id:10122,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"ليبيريا",img:`${FLAGS}/lr.png`},

// ╔══════════════════════════════════════╗
// ║  أعلام أوقيانوسيا + متفرقة (15)    ║
// ╚══════════════════════════════════════╝
{id:10123,cat:"أعلام",diff:"easy",q:"ما الدولة صاحبة هذا العلم؟",a:"أستراليا",img:`${FLAGS}/au.png`},
{id:10124,cat:"أعلام",diff:"medium",q:"ما الدولة صاحبة هذا العلم؟",a:"نيوزيلندا",img:`${FLAGS}/nz.png`},
{id:10125,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"فيجي",img:`${FLAGS}/fj.png`},
{id:10126,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"بابوا غينيا الجديدة",img:`${FLAGS}/pg.png`},
{id:10127,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"آيسلندا",img:`${FLAGS}/is.png`},
{id:10128,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"مالطا",img:`${FLAGS}/mt.png`},
{id:10129,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"قبرص",img:`${FLAGS}/cy.png`},
{id:10130,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"لوكسمبورغ",img:`${FLAGS}/lu.png`},
{id:10131,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"سلوفينيا",img:`${FLAGS}/si.png`},
{id:10132,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"ألبانيا",img:`${FLAGS}/al.png`},
{id:10133,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"مقدونيا الشمالية",img:`${FLAGS}/mk.png`},
{id:10134,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"الجبل الأسود",img:`${FLAGS}/me.png`},
{id:10135,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"البوسنة والهرسك",img:`${FLAGS}/ba.png`},
{id:10136,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"جورجيا",img:`${FLAGS}/ge.png`},
{id:10137,cat:"أعلام",diff:"hard",q:"ما الدولة صاحبة هذا العلم؟",a:"أرمينيا",img:`${FLAGS}/am.png`},

// ╔══════════════════════════════════════╗
// ║  معالم — Landmarks (80)             ║
// ╚══════════════════════════════════════╝
{id:10138,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"برج إيفل",img:`${WIKI}/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/320px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg`},
{id:10139,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"أهرامات الجيزة",img:`${WIKI}/e/e3/Kheops-Pyramid.jpg/320px-Kheops-Pyramid.jpg`},
{id:10140,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"تمثال الحرية",img:`${WIKI}/d/dd/Lady_Liberty_under_a_blue_sky_%28cropped%29.jpg/240px-Lady_Liberty_under_a_blue_sky_%28cropped%29.jpg`},
{id:10141,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"تاج محل",img:`${WIKI}/1/1d/Taj_Mahal_%28Edited%29.jpeg/320px-Taj_Mahal_%28Edited%29.jpeg`},
{id:10142,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"سور الصين العظيم",img:`${WIKI}/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/320px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg`},
{id:10143,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"الكولوسيوم",img:`${WIKI}/d/d8/Colosseum_in_Rome-April_2007-1-_copie_2B.jpg/320px-Colosseum_in_Rome-April_2007-1-_copie_2B.jpg`},
{id:10144,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"برج بيزا المائل",img:`${WIKI}/6/66/The_Leaning_Tower_of_Pisa_SB.jpeg/220px-The_Leaning_Tower_of_Pisa_SB.jpeg`},
{id:10145,cat:"معالم",diff:"medium",q:"ما اسم هذا المعلم؟",a:"ماتشو بيتشو",img:`${WIKI}/e/eb/Machu_Picchu%2C_Peru.jpg/320px-Machu_Picchu%2C_Peru.jpg`},
{id:10146,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"المسجد الحرام",img:`${WIKI}/e/e0/Masjid_al-Haram%2C_2_April_2015.jpg/320px-Masjid_al-Haram%2C_2_April_2015.jpg`},
{id:10147,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"برج خليفة",img:`${WIKI}/9/93/Burj_Khalifa.jpg/180px-Burj_Khalifa.jpg`},
{id:10148,cat:"معالم",diff:"medium",q:"ما اسم هذا المعلم؟",a:"دار الأوبرا في سيدني",img:`${WIKI}/a/a0/Sydney_Australia._%2821339175489%29.jpg/320px-Sydney_Australia._%2821339175489%29.jpg`},
{id:10149,cat:"معالم",diff:"medium",q:"ما اسم هذا المعلم؟",a:"كنيسة القديس بطرس",img:`${WIKI}/f/f5/Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg/320px-Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg`},
{id:10150,cat:"معالم",diff:"medium",q:"ما اسم هذا المعلم؟",a:"أبو الهول",img:`${WIKI}/f/f6/Great_Sphinx_of_Giza_-_20080716a.jpg/320px-Great_Sphinx_of_Giza_-_20080716a.jpg`},
{id:10151,cat:"معالم",diff:"medium",q:"ما اسم هذا المعلم؟",a:"البتراء",img:`${WIKI}/1/1c/Al-Khazneh_%28Petra%29.jpg/220px-Al-Khazneh_%28Petra%29.jpg`},
{id:10152,cat:"معالم",diff:"medium",q:"ما اسم هذا المعلم؟",a:"قصر الحمراء",img:`${WIKI}/d/de/Alhambra-de-Grenade.jpg/320px-Alhambra-de-Grenade.jpg`},
{id:10153,cat:"معالم",diff:"medium",q:"ما اسم هذا المعلم؟",a:"ساعة بيغ بن",img:`${WIKI}/9/93/Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007.jpg/180px-Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007.jpg`},
{id:10154,cat:"معالم",diff:"medium",q:"ما اسم هذا المعلم؟",a:"جبل فوجي",img:`${WIKI}/1/1b/080103_hakridge_fuji.jpg/320px-080103_hakridge_fuji.jpg`},
{id:10155,cat:"معالم",diff:"hard",q:"ما اسم هذا المعلم؟",a:"أنغكور وات",img:`${WIKI}/4/44/Ankor_Wat_temple.jpg/320px-Ankor_Wat_temple.jpg`},
{id:10156,cat:"معالم",diff:"hard",q:"ما اسم هذا المعلم؟",a:"تشيتشن إيتزا",img:`${WIKI}/1/1c/Chichen-Itza-Castillo-Seen-From-East.JPG/320px-Chichen-Itza-Castillo-Seen-From-East.JPG`},
{id:10157,cat:"معالم",diff:"easy",q:"ما اسم هذا المعلم؟",a:"المسجد النبوي",img:`${WIKI}/3/30/Al-Masjid_AL-Nabawi_in_Madinah_-_Saudi_Arabia.jpg/320px-Al-Masjid_AL-Nabawi_in_Madinah_-_Saudi_Arabia.jpg`},
];
